export const FILTER_REPOSITORIES_SUCCESS = 'FILTER_REPOSITORIES_SUCCESS';
export const FILTER_REPOSITORIES = 'FILTER_REPOSITORIES';
export const SEARCH_REPOSITORIES = 'SEARCH_REPOSITORIES';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_PAGE_SUCCESS = 'CHANGE_PAGE_SUCCESS';
export const SEARCH_REPOSITORIES_SUCCESS= 'SEARCH_REPOSITORIES_SUCCESS';
export const GET_USER_REPOSITORIES_REQUEST = 'GET_USER_REPOSITORIES_REQUEST';
export const GET_USER_REPOSITORIES_SUCCESS = 'GET_USER_REPOSITORIES_SUCCESS';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_REQUEST_SUCCESS = 'GET_USER_REQUEST_SUCCESS';
export const GET_USER_REPOSITORIES_FAILED = 'GET_USER_REPOSITORIES_FAILED';

